<?php

namespace App\Tests\Service\Security;

use App\Entity\User;
use App\Repository\UserRepository;
use App\Service\Security\UserPasswordHash;
use App\Tests\Repository\InMemoryUserRepository;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;

class UserPasswordHashTest extends KernelTestCase
{
    private readonly UserPasswordHash $service;
    private string $hashedPassword = 'hassed_password';

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $userPasswordHasherInterface = $this->createMock(UserPasswordHasherInterface::class);
        $userPasswordHasherInterface->expects($this->any())
            ->method('hashPassword')
            ->willReturn($this->hashedPassword);

        $this->service = new UserPasswordHash($userPasswordHasherInterface);
    }

    public function testHash(): void
    {
        $user = new User();
        $user->setPassword('monpass');

        $response = $this->service->hash($user);

        self::assertNotEquals($user->getPassword(), $response);
        self::assertEquals($this->hashedPassword, $response);
    }
}
