# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    connector_email: '%env(CONNECTOR_EMAIL)%'
    connector_password: '%env(CONNECTOR_PASSWORD)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Repository\AddressRepository:
        class: App\Repository\AddressRepository
        arguments:
            - '@doctrine'
            - App\Entity\Address

    App\Repository\AssociationRepository:
        class: App\Repository\AssociationRepository
        arguments:
            - '@doctrine'
            - App\Entity\Association

    App\Repository\MessageRepository:
        class: App\Repository\MessageRepository
        arguments:
            - '@doctrine'
            - App\Entity\Message

    App\Repository\NotificationRepository:
        class: App\Repository\NotificationRepository
        arguments:
            - '@doctrine'
            - App\Entity\Notification

    App\Repository\OrderRepository:
        class: App\Repository\OrderRepository
        arguments:
            - '@doctrine'
            - App\Entity\Order

    App\Repository\ProofDocumentRepository:
        class: App\Repository\ProofDocumentRepository
        arguments:
            - '@doctrine'
            - App\Entity\ProofDocument

    App\Repository\RescueRepository:
        class: App\Repository\RescueRepository
        arguments:
            - '@doctrine'
            - App\Entity\Rescue

    App\Repository\UserRepository:
        class: App\Repository\UserRepository
        arguments:
            - '@doctrine'
            - App\Entity\User

    App\Repository\WithdrawalDateRepository:
        class: App\Repository\WithdrawalDateRepository
        arguments:
            - '@doctrine'
            - App\Entity\WithdrawalDate

    App\Repository\WithdrawalPointRepository:
        class: App\Repository\WithdrawalPointRepository
        arguments:
            - '@doctrine'
            - App\Entity\WithdrawalPoint
