<?php

namespace App\Tests\Service\Security\Token;

use App\Entity\TokensRegistry;
use App\Service\Security\Token\TokenConfirmRegistrationCreate;
use App\Tests\Repository\InMemoryTokensRegistryRepository;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

class TokenConfirmRegistrationCreateTest extends KernelTestCase
{
    private readonly TokenConfirmRegistrationCreate $service;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $tokensRegistryRepo = new InMemoryTokensRegistryRepository();
        $this->service = new TokenConfirmRegistrationCreate($tokensRegistryRepo);
    }

    /**
     * Test for create a new TokenRegistry
     * @return void
     * @throws \Exception
     */
    public function testCreateNewRegistry(): void
    {
        $response = $this->service->create();

        self::assertInstanceOf(TokensRegistry::class, $response);
        self::assertNotNull($response->getConfirmRegister());
    }

    /**
     * Test with an existing TokenRegistry, update existing token with a new
     * @return void
     * @throws \Exception
     */
    public function testUpdateExistingRegistry(): void
    {
        $oldToken = 'monancientoken';

        $existingRegistry = new TokensRegistry();
        $existingRegistry->setConfirmRegister($oldToken);

        self::assertEquals($oldToken, $existingRegistry->getConfirmRegister());

        $response = $this->service->create($existingRegistry);

        self::assertInstanceOf(TokensRegistry::class, $response);
        self::assertNotEquals($oldToken, $response->getConfirmRegister());
    }
}
